---
- name: Check for existing Nessus Agent installation.
  stat:
    path: /opt/nessus_agent/sbin/nessuscli
  register: nessus_agent_installed

- debug:
    var: nessus_agent_installed
    verbosity: 1

# Skip all the download, copy, and install stuff if the files already exist.
- block:

  - import_tasks: redhat.yml
    when: ansible_os_family == 'RedHat'

  - import_tasks: ubuntu.yml
    when: ansible_distribution == 'Ubuntu'

  - name: Check agent link status.
    command: /opt/nessus_agent/sbin/nessuscli agent status
    become: yes
    ignore_errors: yes
    register: nessus_agent_link

  - name: Link Nessus Agent.
    command: >
        /opt/nessus_agent/sbin/nessuscli agent link
        --key={{ nessus_agent_key }}
        --host={{ nessus_agent_host }}
        --port={{ nessus_agent_port }}
        --groups="{{ nessus_agent_group }}"
    become: yes
    when: nessus_agent_link is failed
    notify: restart nessusagent
    ignore_errors: "{{ ansible_check_mode }}"

  - name: Ensure nessusagent is enabled and started.
    service:
      name: nessusagent
      state: started
      enabled: yes
    ignore_errors: "{{ ansible_check_mode }}"

  when: not nessus_agent_installed.stat.exists
